import java.time.LocalDate;

public class Program {
    public static void main(String[] args) {
        Department d1 = new Department();
        d1.departmentId = 1;
        d1.departmentName = "Sale";
        Department d2 = new Department();
        d2.departmentId = 2;
        d2.departmentName = "Marketing";
        Department d3 = new Department();
        d3.departmentId = 3;
        d3.departmentName = "IT";
        Position p1 = new Position();
        p1.positionId = 1;
        p1.positionName = PositionName.Dev;
        Position p2 = new Position();
        p2.positionId = 2;
        p2.positionName = PositionName.PM;
        Position p3 = new Position();
        p3.positionId = 3;
        p3.positionName = PositionName.Test;
        Account a1 = new Account();
        a1.accountId = 1;
        a1.email = "hung@gmail.com";
        a1.userName = "user1";
        a1.fullName = "Mạnh Hùng";
        a1.departmentId = d1;
        a1.positionId = p1;
        a1.createDate = LocalDate.now();
        Account a2 = new Account();
        a2.accountId = 2;
        a2.email = "son@gmail.com";
        a2.userName = "user2";
        a2.fullName = "Hồng Sơn";
        a2.departmentId = d2;
        a2.positionId = p2;
        a2.createDate = LocalDate.now();
        Account a3 = new Account();
        a3.accountId =3;
        a3.email = "dat@gmail.com";
        a3.userName = "user3";
        a3.fullName = "Nguyễn Đạt";
        a3.departmentId = d3;
        a3.positionId = p3;
        a3.createDate = LocalDate.now();
        Group g1 = new Group();
        g1.groupId = 1;
        g1.groupName = "Java";
        g1.creatorId = a1;
        g1.createDate = LocalDate.now();
        Group g2 = new Group();
        g2.groupId = 2;
        g2.groupName = "SQL";
        g2.creatorId = a2;
        g2.createDate = LocalDate.now();
        Group g3 = new Group();
        g3.groupId = 3;
        g3.groupName = "Text";
        g3.creatorId = a3;
        g3.createDate = LocalDate.now();
        GroupAccount ga1 = new GroupAccount();
        ga1.groupId = g1;
        ga1.accountId = a1;
        ga1.joinDate = LocalDate.now();
        GroupAccount ga2 = new GroupAccount();
        ga2.groupId = g2;
        ga2.accountId = a2;
        ga2.joinDate = LocalDate.now();
        GroupAccount ga3 = new GroupAccount();
        ga3.groupId = g3;
        ga3.accountId = a3;
        ga3.joinDate = LocalDate.now();
        TypeQuestion tq1 = new TypeQuestion();
        tq1.typeId = 1;
        tq1.typeName = TypeName.Essay;
        TypeQuestion tq2 = new TypeQuestion();
        tq2.typeId = 2;
        tq2.typeName = TypeName.Multiple_Choice;
        TypeQuestion tq3 = new TypeQuestion();
        tq3.typeId = 3;
        tq3.typeName = TypeName.Essay;
        CategoryQuestion cq1 = new CategoryQuestion();
        cq1.categoryId = 1;
        cq1.categoryName = "Java";
        CategoryQuestion cq2 = new CategoryQuestion();
        cq2.categoryId = 2;
        cq2.categoryName = "SQL";
        CategoryQuestion cq3 = new CategoryQuestion();
        cq3.categoryId = 3;
        cq3.categoryName = "Text";
        Question q1 = new Question();
        q1.questionId = 1;
        q1.conTent = "Java Là Gì";
        q1.categoryId = cq1;
        q1.typeId = tq1;
        q1.creatorId = a1;
        q1.createDate = LocalDate.now();
        Question q2 = new Question();
        q2.questionId = 2;
        q2.conTent = "SQL Là Gì";
        q2.categoryId = cq2;
        q2.typeId = tq2;
        q2.creatorId = a2;
        q2.createDate = LocalDate.now();
        Question q3 = new Question();
        q3.questionId = 3;
        q3.conTent = "Text Care?";
        q3.categoryId = cq3;
        q3.typeId = tq3;
        q3.creatorId = a3;
        q3.createDate = LocalDate.now();
        Answer an1 = new Answer();
        an1.answerId = 1;
        an1.conTent = "Java là ngôn ngữ";
        an1.questionId = q1;
        an1.isCorrect = true;
        Answer an2 = new Answer();
        an2.answerId = 1;
        an2.conTent = "SQL là ngôn ngữ truy vấn";
        an2.questionId = q2;
        an2.isCorrect = true;
        Answer an3 = new Answer();
        an3.answerId = 3;
        an3.conTent = "Sai";
        an3.questionId = q3;
        an3.isCorrect = false;
        Exam ex1 = new Exam();
        ex1.examId = 1;
        ex1.code = "E01";
        ex1.title = "Java Basic";
        ex1.categoryId = cq1;
        ex1.duration = 90;
        ex1.creatorId = a1;
        ex1.createDate = LocalDate.now();
        Exam ex2 = new Exam();
        ex2.examId = 2;
        ex2.code = "E02";
        ex2.title = "SQL Basic";
        ex2.categoryId = cq2;
        ex2.duration = 90;
        ex2.creatorId = a2;
        ex2.createDate = LocalDate.now();
        Exam ex3 = new Exam();
        ex3.examId = 3;
        ex3.code = "E03";
        ex3.title = "Text Basic";
        ex3.categoryId = cq3;
        ex3.duration = 60;
        ex3.creatorId = a3;
        ex3.createDate = LocalDate.now();
        ExamQuestion eq1 = new ExamQuestion();
        eq1.examId = ex1;
        eq1.questionId = q1;
        ExamQuestion eq2 = new ExamQuestion();
        eq2.examId = ex2;
        eq2.questionId = q2;
        ExamQuestion eq3 = new ExamQuestion();
        eq3.examId = ex3;
        eq3.questionId = q3;
        System.out.println(d1.departmentName);
        System.out.println(p1.positionName);
        System.out.println(a1.fullName);
        System.out.println(g1.groupName);
        System.out.println(ga1.groupId);
        System.out.println(tq1.typeName);
        System.out.println(cq1.categoryName);
        System.out.println(q1.questionId);
        System.out.println(an1.answerId);
        System.out.println(ex1.examId);
        System.out.println(eq1.questionId);


    }
}
